"""
Batch 2B Expansion — 7 Band & Kettlebell Exercises
Real authored activation matrices for all 27 muscles.
Activation scale: 0 (none) to 5 (maximal).

Muscles (by ID):
 1 Forearms, 2 Biceps, 3 Triceps, 4 Deltoids, 5 Front/Anterior Delt,
 6 Rear/Posterior Delt, 7 Side/Lateral Delt, 8 Neck, 9 Traps,
10 Upper Traps, 11 Mid Traps, 12 Lower Traps, 13 Upper Back,
14 Middle Back, 15 Lower Back, 16 Lats, 17 Pectorals, 18 Obliques,
19 Abs, 20 Glutes, 21 Adductors, 22 Abductors, 23 Quads,
24 Hamstrings, 25 Shins, 26 Calves, 27 Hands/Grip
"""

BATCH2B_EXERCISES = {
    "Band Curl": {
        "activation": {
            "Forearms": 2, "Biceps": 5, "Triceps": 0, "Deltoids": 1,
            "Front/Anterior Delt": 1, "Rear/Posterior Delt": 0,
            "Side/Lateral Delt": 0, "Neck": 0, "Traps": 0,
            "Upper Traps": 0, "Mid Traps": 0, "Lower Traps": 0,
            "Upper Back": 0, "Middle Back": 0, "Lower Back": 0,
            "Lats": 0, "Pectorals": 0, "Obliques": 0, "Abs": 0,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.2, "Biceps": 1.0, "Triceps": 0.0, "Deltoids": 0.06,
            "Front/Anterior Delt": 0.06, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.15,
        },
        "bottleneck": {
            "Forearms": 0.15, "Biceps": 1.0, "Triceps": 0.0, "Deltoids": 0.0,
            "Front/Anterior Delt": 0.05, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.1,
        },
        "stabilization": {
            "Forearms": 0.15, "Biceps": 0.1, "Triceps": 0.0, "Deltoids": 0.08,
            "Front/Anterior Delt": 0.08, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.05,
            "Upper Traps": 0.05, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.05,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.05, "Abs": 0.1,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.15,
        },
        "tags": ["pull"],
        "equipment": ["band"],
        "biomechanics": {
            "implement_type": "band",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "elastic",
            "resistance_direction": "vertical",
            "grip_style": "underhand",
            "bench_angle": None,
            "stability_demand": 0.2,
            "stretch_bias": None,
            "shortened_bias": 0.7,
            "convergence_arc": None,
            "humeral_plane": "sagittal",
            "elbow_path": "fixed",
            "movement_family": "curl",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Band Pushdown": {
        "activation": {
            "Forearms": 1, "Biceps": 0, "Triceps": 5, "Deltoids": 1,
            "Front/Anterior Delt": 1, "Rear/Posterior Delt": 0,
            "Side/Lateral Delt": 0, "Neck": 0, "Traps": 0,
            "Upper Traps": 0, "Mid Traps": 0, "Lower Traps": 0,
            "Upper Back": 0, "Middle Back": 0, "Lower Back": 0,
            "Lats": 1, "Pectorals": 0, "Obliques": 0, "Abs": 1,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.08, "Biceps": 0.0, "Triceps": 1.0, "Deltoids": 0.06,
            "Front/Anterior Delt": 0.06, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.06, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.06,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.12,
        },
        "bottleneck": {
            "Forearms": 0.05, "Biceps": 0.0, "Triceps": 1.0, "Deltoids": 0.0,
            "Front/Anterior Delt": 0.05, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.05, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.08,
        },
        "stabilization": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 0.15, "Deltoids": 0.08,
            "Front/Anterior Delt": 0.08, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.05,
            "Upper Traps": 0.05, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.05,
            "Lats": 0.08, "Pectorals": 0.0, "Obliques": 0.05, "Abs": 0.1,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.12,
        },
        "tags": ["push"],
        "equipment": ["band"],
        "biomechanics": {
            "implement_type": "band",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "elastic",
            "resistance_direction": "vertical",
            "grip_style": "overhand",
            "bench_angle": None,
            "stability_demand": 0.2,
            "stretch_bias": 0.3,
            "shortened_bias": 0.7,
            "convergence_arc": None,
            "humeral_plane": "sagittal",
            "elbow_path": "fixed",
            "movement_family": "extension",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Band Pallof Press": {
        "activation": {
            "Forearms": 1, "Biceps": 0, "Triceps": 1, "Deltoids": 2,
            "Front/Anterior Delt": 2, "Rear/Posterior Delt": 1,
            "Side/Lateral Delt": 1, "Neck": 1, "Traps": 1,
            "Upper Traps": 1, "Mid Traps": 1, "Lower Traps": 1,
            "Upper Back": 1, "Middle Back": 1, "Lower Back": 2,
            "Lats": 1, "Pectorals": 1, "Obliques": 4, "Abs": 4,
            "Glutes": 2, "Adductors": 1, "Abductors": 1,
            "Quads": 1, "Hamstrings": 1, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.08, "Biceps": 0.0, "Triceps": 0.08, "Deltoids": 0.15,
            "Front/Anterior Delt": 0.15, "Rear/Posterior Delt": 0.08,
            "Side/Lateral Delt": 0.08, "Neck": 0.05, "Traps": 0.08,
            "Upper Traps": 0.06, "Mid Traps": 0.08, "Lower Traps": 0.06,
            "Upper Back": 0.08, "Middle Back": 0.06, "Lower Back": 0.15,
            "Lats": 0.08, "Pectorals": 0.08, "Obliques": 0.8, "Abs": 0.8,
            "Glutes": 0.2, "Adductors": 0.08, "Abductors": 0.08,
            "Quads": 0.06, "Hamstrings": 0.06, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.15,
        },
        "bottleneck": {
            "Forearms": 0.05, "Biceps": 0.0, "Triceps": 0.05, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.1, "Rear/Posterior Delt": 0.05,
            "Side/Lateral Delt": 0.05, "Neck": 0.0, "Traps": 0.05,
            "Upper Traps": 0.05, "Mid Traps": 0.05, "Lower Traps": 0.05,
            "Upper Back": 0.05, "Middle Back": 0.05, "Lower Back": 0.1,
            "Lats": 0.05, "Pectorals": 0.05, "Obliques": 0.7, "Abs": 0.7,
            "Glutes": 0.1, "Adductors": 0.05, "Abductors": 0.05,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.1,
        },
        "stabilization": {
            "Forearms": 0.1, "Biceps": 0.05, "Triceps": 0.1, "Deltoids": 0.15,
            "Front/Anterior Delt": 0.15, "Rear/Posterior Delt": 0.1,
            "Side/Lateral Delt": 0.1, "Neck": 0.05, "Traps": 0.1,
            "Upper Traps": 0.08, "Mid Traps": 0.1, "Lower Traps": 0.08,
            "Upper Back": 0.1, "Middle Back": 0.08, "Lower Back": 0.2,
            "Lats": 0.1, "Pectorals": 0.1, "Obliques": 0.35, "Abs": 0.35,
            "Glutes": 0.2, "Adductors": 0.1, "Abductors": 0.1,
            "Quads": 0.1, "Hamstrings": 0.1, "Shins": 0.0, "Calves": 0.05,
            "Hands/Grip": 0.15,
        },
        "tags": ["carry"],
        "equipment": ["band"],
        "biomechanics": {
            "implement_type": "band",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "elastic",
            "resistance_direction": "horizontal",
            "grip_style": "handle",
            "bench_angle": None,
            "stability_demand": 0.6,
            "stretch_bias": None,
            "shortened_bias": None,
            "convergence_arc": None,
            "humeral_plane": "transverse",
            "elbow_path": "fixed",
            "movement_family": "press",
            "pattern_class": "compound",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Kettlebell Goblet Squat": {
        "activation": {
            "Forearms": 2, "Biceps": 2, "Triceps": 0, "Deltoids": 2,
            "Front/Anterior Delt": 2, "Rear/Posterior Delt": 0,
            "Side/Lateral Delt": 0, "Neck": 0, "Traps": 1,
            "Upper Traps": 1, "Mid Traps": 1, "Lower Traps": 0,
            "Upper Back": 2, "Middle Back": 1, "Lower Back": 2,
            "Lats": 0, "Pectorals": 0, "Obliques": 1, "Abs": 3,
            "Glutes": 4, "Adductors": 3, "Abductors": 2,
            "Quads": 5, "Hamstrings": 2, "Shins": 1, "Calves": 1,
            "Hands/Grip": 3,
        },
        "role_weighted": {
            "Forearms": 0.15, "Biceps": 0.15, "Triceps": 0.0, "Deltoids": 0.15,
            "Front/Anterior Delt": 0.15, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.08,
            "Upper Traps": 0.08, "Mid Traps": 0.06, "Lower Traps": 0.0,
            "Upper Back": 0.15, "Middle Back": 0.08, "Lower Back": 0.2,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.08, "Abs": 0.3,
            "Glutes": 0.7, "Adductors": 0.3, "Abductors": 0.2,
            "Quads": 1.0, "Hamstrings": 0.2, "Shins": 0.06, "Calves": 0.08,
            "Hands/Grip": 0.25,
        },
        "bottleneck": {
            "Forearms": 0.1, "Biceps": 0.1, "Triceps": 0.0, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.1, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.05,
            "Upper Traps": 0.05, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.1, "Middle Back": 0.05, "Lower Back": 0.15,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.05, "Abs": 0.2,
            "Glutes": 0.5, "Adductors": 0.2, "Abductors": 0.1,
            "Quads": 1.0, "Hamstrings": 0.1, "Shins": 0.0, "Calves": 0.05,
            "Hands/Grip": 0.2,
        },
        "stabilization": {
            "Forearms": 0.15, "Biceps": 0.15, "Triceps": 0.05, "Deltoids": 0.15,
            "Front/Anterior Delt": 0.15, "Rear/Posterior Delt": 0.05,
            "Side/Lateral Delt": 0.05, "Neck": 0.05, "Traps": 0.1,
            "Upper Traps": 0.1, "Mid Traps": 0.08, "Lower Traps": 0.05,
            "Upper Back": 0.15, "Middle Back": 0.1, "Lower Back": 0.25,
            "Lats": 0.05, "Pectorals": 0.0, "Obliques": 0.15, "Abs": 0.3,
            "Glutes": 0.3, "Adductors": 0.2, "Abductors": 0.15,
            "Quads": 0.25, "Hamstrings": 0.15, "Shins": 0.05, "Calves": 0.1,
            "Hands/Grip": 0.25,
        },
        "tags": ["squat"],
        "equipment": ["kettlebell"],
        "biomechanics": {
            "implement_type": "kettlebell",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "gravity",
            "resistance_direction": "vertical",
            "grip_style": "neutral",
            "bench_angle": None,
            "stability_demand": 0.45,
            "stretch_bias": 0.6,
            "shortened_bias": 0.3,
            "convergence_arc": None,
            "humeral_plane": None,
            "elbow_path": None,
            "movement_family": "squat",
            "pattern_class": "compound",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Kettlebell Press": {
        "activation": {
            "Forearms": 2, "Biceps": 1, "Triceps": 4, "Deltoids": 4,
            "Front/Anterior Delt": 5, "Rear/Posterior Delt": 1,
            "Side/Lateral Delt": 3, "Neck": 1, "Traps": 3,
            "Upper Traps": 3, "Mid Traps": 2, "Lower Traps": 2,
            "Upper Back": 1, "Middle Back": 0, "Lower Back": 1,
            "Lats": 1, "Pectorals": 2, "Obliques": 2, "Abs": 2,
            "Glutes": 1, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 3,
        },
        "role_weighted": {
            "Forearms": 0.15, "Biceps": 0.06, "Triceps": 0.6, "Deltoids": 0.7,
            "Front/Anterior Delt": 1.0, "Rear/Posterior Delt": 0.08,
            "Side/Lateral Delt": 0.35, "Neck": 0.05, "Traps": 0.3,
            "Upper Traps": 0.3, "Mid Traps": 0.15, "Lower Traps": 0.15,
            "Upper Back": 0.08, "Middle Back": 0.0, "Lower Back": 0.08,
            "Lats": 0.06, "Pectorals": 0.15, "Obliques": 0.15, "Abs": 0.2,
            "Glutes": 0.06, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.25,
        },
        "bottleneck": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 0.4, "Deltoids": 0.5,
            "Front/Anterior Delt": 1.0, "Rear/Posterior Delt": 0.05,
            "Side/Lateral Delt": 0.2, "Neck": 0.0, "Traps": 0.15,
            "Upper Traps": 0.15, "Mid Traps": 0.1, "Lower Traps": 0.1,
            "Upper Back": 0.05, "Middle Back": 0.0, "Lower Back": 0.05,
            "Lats": 0.0, "Pectorals": 0.1, "Obliques": 0.1, "Abs": 0.1,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.15,
        },
        "stabilization": {
            "Forearms": 0.2, "Biceps": 0.1, "Triceps": 0.2, "Deltoids": 0.3,
            "Front/Anterior Delt": 0.3, "Rear/Posterior Delt": 0.15,
            "Side/Lateral Delt": 0.2, "Neck": 0.05, "Traps": 0.2,
            "Upper Traps": 0.2, "Mid Traps": 0.15, "Lower Traps": 0.15,
            "Upper Back": 0.1, "Middle Back": 0.05, "Lower Back": 0.15,
            "Lats": 0.1, "Pectorals": 0.1, "Obliques": 0.2, "Abs": 0.25,
            "Glutes": 0.1, "Adductors": 0.05, "Abductors": 0.05,
            "Quads": 0.05, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.05,
            "Hands/Grip": 0.3,
        },
        "tags": ["push"],
        "equipment": ["kettlebell"],
        "biomechanics": {
            "implement_type": "kettlebell",
            "body_position": "standing",
            "laterality": "unilateral",
            "resistance_origin": "gravity",
            "resistance_direction": "vertical",
            "grip_style": "neutral",
            "bench_angle": None,
            "stability_demand": 0.6,
            "stretch_bias": 0.4,
            "shortened_bias": 0.3,
            "convergence_arc": None,
            "humeral_plane": "scapular",
            "elbow_path": "free",
            "movement_family": "press",
            "pattern_class": "compound",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Kettlebell Row": {
        "activation": {
            "Forearms": 3, "Biceps": 3, "Triceps": 0, "Deltoids": 2,
            "Front/Anterior Delt": 0, "Rear/Posterior Delt": 3,
            "Side/Lateral Delt": 1, "Neck": 0, "Traps": 3,
            "Upper Traps": 2, "Mid Traps": 3, "Lower Traps": 2,
            "Upper Back": 3, "Middle Back": 3, "Lower Back": 2,
            "Lats": 4, "Pectorals": 0, "Obliques": 1, "Abs": 1,
            "Glutes": 1, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 1, "Shins": 0, "Calves": 0,
            "Hands/Grip": 3,
        },
        "role_weighted": {
            "Forearms": 0.25, "Biceps": 0.3, "Triceps": 0.0, "Deltoids": 0.2,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 0.3,
            "Side/Lateral Delt": 0.06, "Neck": 0.0, "Traps": 0.3,
            "Upper Traps": 0.2, "Mid Traps": 0.3, "Lower Traps": 0.2,
            "Upper Back": 0.35, "Middle Back": 0.3, "Lower Back": 0.15,
            "Lats": 1.0, "Pectorals": 0.0, "Obliques": 0.08, "Abs": 0.08,
            "Glutes": 0.06, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.06, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.3,
        },
        "bottleneck": {
            "Forearms": 0.15, "Biceps": 0.2, "Triceps": 0.0, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 0.2,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.15,
            "Upper Traps": 0.1, "Mid Traps": 0.2, "Lower Traps": 0.1,
            "Upper Back": 0.25, "Middle Back": 0.2, "Lower Back": 0.1,
            "Lats": 1.0, "Pectorals": 0.0, "Obliques": 0.05, "Abs": 0.05,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "stabilization": {
            "Forearms": 0.2, "Biceps": 0.15, "Triceps": 0.0, "Deltoids": 0.15,
            "Front/Anterior Delt": 0.05, "Rear/Posterior Delt": 0.15,
            "Side/Lateral Delt": 0.05, "Neck": 0.0, "Traps": 0.15,
            "Upper Traps": 0.1, "Mid Traps": 0.15, "Lower Traps": 0.1,
            "Upper Back": 0.15, "Middle Back": 0.15, "Lower Back": 0.2,
            "Lats": 0.2, "Pectorals": 0.0, "Obliques": 0.15, "Abs": 0.15,
            "Glutes": 0.1, "Adductors": 0.05, "Abductors": 0.05,
            "Quads": 0.05, "Hamstrings": 0.1, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.25,
        },
        "tags": ["pull"],
        "equipment": ["kettlebell"],
        "biomechanics": {
            "implement_type": "kettlebell",
            "body_position": "standing",
            "laterality": "unilateral",
            "resistance_origin": "gravity",
            "resistance_direction": "vertical",
            "grip_style": "neutral",
            "bench_angle": None,
            "stability_demand": 0.5,
            "stretch_bias": 0.5,
            "shortened_bias": 0.4,
            "convergence_arc": None,
            "humeral_plane": "sagittal",
            "elbow_path": "free",
            "movement_family": "row",
            "pattern_class": "compound",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Kettlebell Swing": {
        "activation": {
            "Forearms": 3, "Biceps": 1, "Triceps": 0, "Deltoids": 2,
            "Front/Anterior Delt": 2, "Rear/Posterior Delt": 1,
            "Side/Lateral Delt": 1, "Neck": 1, "Traps": 2,
            "Upper Traps": 2, "Mid Traps": 1, "Lower Traps": 1,
            "Upper Back": 2, "Middle Back": 2, "Lower Back": 4,
            "Lats": 2, "Pectorals": 0, "Obliques": 2, "Abs": 3,
            "Glutes": 5, "Adductors": 2, "Abductors": 2,
            "Quads": 3, "Hamstrings": 4, "Shins": 1, "Calves": 2,
            "Hands/Grip": 4,
        },
        "role_weighted": {
            "Forearms": 0.2, "Biceps": 0.05, "Triceps": 0.0, "Deltoids": 0.15,
            "Front/Anterior Delt": 0.15, "Rear/Posterior Delt": 0.08,
            "Side/Lateral Delt": 0.05, "Neck": 0.05, "Traps": 0.15,
            "Upper Traps": 0.15, "Mid Traps": 0.08, "Lower Traps": 0.06,
            "Upper Back": 0.15, "Middle Back": 0.15, "Lower Back": 0.55,
            "Lats": 0.15, "Pectorals": 0.0, "Obliques": 0.15, "Abs": 0.3,
            "Glutes": 1.0, "Adductors": 0.15, "Abductors": 0.15,
            "Quads": 0.3, "Hamstrings": 0.65, "Shins": 0.06, "Calves": 0.15,
            "Hands/Grip": 0.35,
        },
        "bottleneck": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.08,
            "Front/Anterior Delt": 0.08, "Rear/Posterior Delt": 0.05,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.08,
            "Upper Traps": 0.08, "Mid Traps": 0.05, "Lower Traps": 0.05,
            "Upper Back": 0.1, "Middle Back": 0.1, "Lower Back": 0.4,
            "Lats": 0.1, "Pectorals": 0.0, "Obliques": 0.1, "Abs": 0.2,
            "Glutes": 1.0, "Adductors": 0.1, "Abductors": 0.1,
            "Quads": 0.15, "Hamstrings": 0.45, "Shins": 0.0, "Calves": 0.1,
            "Hands/Grip": 0.25,
        },
        "stabilization": {
            "Forearms": 0.2, "Biceps": 0.08, "Triceps": 0.05, "Deltoids": 0.15,
            "Front/Anterior Delt": 0.15, "Rear/Posterior Delt": 0.1,
            "Side/Lateral Delt": 0.08, "Neck": 0.05, "Traps": 0.15,
            "Upper Traps": 0.15, "Mid Traps": 0.1, "Lower Traps": 0.08,
            "Upper Back": 0.15, "Middle Back": 0.15, "Lower Back": 0.35,
            "Lats": 0.15, "Pectorals": 0.0, "Obliques": 0.2, "Abs": 0.3,
            "Glutes": 0.35, "Adductors": 0.15, "Abductors": 0.15,
            "Quads": 0.2, "Hamstrings": 0.25, "Shins": 0.05, "Calves": 0.15,
            "Hands/Grip": 0.3,
        },
        "tags": ["hinge"],
        "equipment": ["kettlebell"],
        "biomechanics": {
            "implement_type": "kettlebell",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "gravity",
            "resistance_direction": "vertical",
            "grip_style": "overhand",
            "bench_angle": None,
            "stability_demand": 0.55,
            "stretch_bias": 0.6,
            "shortened_bias": 0.3,
            "convergence_arc": None,
            "humeral_plane": "sagittal",
            "elbow_path": None,
            "movement_family": "hinge",
            "pattern_class": "ballistic",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
}
