"""
Batch 2C Expansion — 3 Advanced Kettlebell/Whole-Body Exercises
Real authored activation matrices for all 27 muscles.
Activation scale: 0 (none) to 5 (maximal).

These are the most biomechanically complex exercises in Batch 2.
Multi-phase, whole-body movements with significant coordination demands.

Muscles (by ID):
 1 Forearms, 2 Biceps, 3 Triceps, 4 Deltoids, 5 Front/Anterior Delt,
 6 Rear/Posterior Delt, 7 Side/Lateral Delt, 8 Neck, 9 Traps,
10 Upper Traps, 11 Mid Traps, 12 Lower Traps, 13 Upper Back,
14 Middle Back, 15 Lower Back, 16 Lats, 17 Pectorals, 18 Obliques,
19 Abs, 20 Glutes, 21 Adductors, 22 Abductors, 23 Quads,
24 Hamstrings, 25 Shins, 26 Calves, 27 Hands/Grip
"""

BATCH2C_EXERCISES = {
    "Kettlebell Clean": {
        "activation": {
            "Forearms": 3, "Biceps": 2, "Triceps": 1, "Deltoids": 2,
            "Front/Anterior Delt": 2, "Rear/Posterior Delt": 1,
            "Side/Lateral Delt": 1, "Neck": 1, "Traps": 3,
            "Upper Traps": 3, "Mid Traps": 2, "Lower Traps": 1,
            "Upper Back": 2, "Middle Back": 2, "Lower Back": 4,
            "Lats": 2, "Pectorals": 0, "Obliques": 2, "Abs": 3,
            "Glutes": 4, "Adductors": 2, "Abductors": 2,
            "Quads": 3, "Hamstrings": 4, "Shins": 1, "Calves": 2,
            "Hands/Grip": 4,
        },
        "role_weighted": {
            "Forearms": 0.25, "Biceps": 0.15, "Triceps": 0.05, "Deltoids": 0.15,
            "Front/Anterior Delt": 0.15, "Rear/Posterior Delt": 0.08,
            "Side/Lateral Delt": 0.06, "Neck": 0.05, "Traps": 0.3,
            "Upper Traps": 0.3, "Mid Traps": 0.15, "Lower Traps": 0.08,
            "Upper Back": 0.15, "Middle Back": 0.15, "Lower Back": 0.5,
            "Lats": 0.15, "Pectorals": 0.0, "Obliques": 0.15, "Abs": 0.3,
            "Glutes": 0.8, "Adductors": 0.15, "Abductors": 0.15,
            "Quads": 0.3, "Hamstrings": 0.6, "Shins": 0.06, "Calves": 0.15,
            "Hands/Grip": 0.4,
        },
        "bottleneck": {
            "Forearms": 0.15, "Biceps": 0.1, "Triceps": 0.0, "Deltoids": 0.08,
            "Front/Anterior Delt": 0.08, "Rear/Posterior Delt": 0.05,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.2,
            "Upper Traps": 0.2, "Mid Traps": 0.1, "Lower Traps": 0.05,
            "Upper Back": 0.1, "Middle Back": 0.1, "Lower Back": 0.35,
            "Lats": 0.1, "Pectorals": 0.0, "Obliques": 0.1, "Abs": 0.2,
            "Glutes": 0.7, "Adductors": 0.1, "Abductors": 0.1,
            "Quads": 0.2, "Hamstrings": 0.4, "Shins": 0.0, "Calves": 0.1,
            "Hands/Grip": 0.3,
        },
        "stabilization": {
            "Forearms": 0.25, "Biceps": 0.15, "Triceps": 0.1, "Deltoids": 0.2,
            "Front/Anterior Delt": 0.2, "Rear/Posterior Delt": 0.1,
            "Side/Lateral Delt": 0.1, "Neck": 0.05, "Traps": 0.2,
            "Upper Traps": 0.2, "Mid Traps": 0.15, "Lower Traps": 0.1,
            "Upper Back": 0.15, "Middle Back": 0.15, "Lower Back": 0.35,
            "Lats": 0.15, "Pectorals": 0.0, "Obliques": 0.2, "Abs": 0.3,
            "Glutes": 0.3, "Adductors": 0.15, "Abductors": 0.15,
            "Quads": 0.2, "Hamstrings": 0.25, "Shins": 0.05, "Calves": 0.15,
            "Hands/Grip": 0.35,
        },
        "tags": ["oly"],
        "equipment": ["kettlebell"],
        "biomechanics": {
            "implement_type": "kettlebell",
            "body_position": "standing",
            "laterality": "unilateral",
            "resistance_origin": "gravity",
            "resistance_direction": "vertical",
            "grip_style": "overhand",
            "bench_angle": None,
            "stability_demand": 0.65,
            "stretch_bias": 0.5,
            "shortened_bias": 0.3,
            "convergence_arc": None,
            "humeral_plane": None,
            "elbow_path": None,
            "movement_family": "olympic",
            "pattern_class": "ballistic",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Kettlebell Snatch": {
        "activation": {
            "Forearms": 3, "Biceps": 2, "Triceps": 2, "Deltoids": 3,
            "Front/Anterior Delt": 3, "Rear/Posterior Delt": 2,
            "Side/Lateral Delt": 2, "Neck": 1, "Traps": 4,
            "Upper Traps": 4, "Mid Traps": 3, "Lower Traps": 2,
            "Upper Back": 3, "Middle Back": 2, "Lower Back": 4,
            "Lats": 2, "Pectorals": 0, "Obliques": 3, "Abs": 3,
            "Glutes": 5, "Adductors": 2, "Abductors": 2,
            "Quads": 3, "Hamstrings": 4, "Shins": 1, "Calves": 2,
            "Hands/Grip": 5,
        },
        "role_weighted": {
            "Forearms": 0.25, "Biceps": 0.1, "Triceps": 0.1, "Deltoids": 0.25,
            "Front/Anterior Delt": 0.25, "Rear/Posterior Delt": 0.15,
            "Side/Lateral Delt": 0.15, "Neck": 0.05, "Traps": 0.4,
            "Upper Traps": 0.4, "Mid Traps": 0.25, "Lower Traps": 0.15,
            "Upper Back": 0.25, "Middle Back": 0.15, "Lower Back": 0.5,
            "Lats": 0.15, "Pectorals": 0.0, "Obliques": 0.2, "Abs": 0.3,
            "Glutes": 1.0, "Adductors": 0.15, "Abductors": 0.15,
            "Quads": 0.3, "Hamstrings": 0.6, "Shins": 0.06, "Calves": 0.15,
            "Hands/Grip": 0.5,
        },
        "bottleneck": {
            "Forearms": 0.2, "Biceps": 0.05, "Triceps": 0.05, "Deltoids": 0.2,
            "Front/Anterior Delt": 0.2, "Rear/Posterior Delt": 0.1,
            "Side/Lateral Delt": 0.1, "Neck": 0.0, "Traps": 0.3,
            "Upper Traps": 0.3, "Mid Traps": 0.15, "Lower Traps": 0.1,
            "Upper Back": 0.15, "Middle Back": 0.1, "Lower Back": 0.35,
            "Lats": 0.1, "Pectorals": 0.0, "Obliques": 0.15, "Abs": 0.2,
            "Glutes": 0.7, "Adductors": 0.1, "Abductors": 0.1,
            "Quads": 0.2, "Hamstrings": 0.4, "Shins": 0.0, "Calves": 0.1,
            "Hands/Grip": 0.45,
        },
        "stabilization": {
            "Forearms": 0.3, "Biceps": 0.1, "Triceps": 0.15, "Deltoids": 0.25,
            "Front/Anterior Delt": 0.25, "Rear/Posterior Delt": 0.15,
            "Side/Lateral Delt": 0.15, "Neck": 0.05, "Traps": 0.25,
            "Upper Traps": 0.25, "Mid Traps": 0.2, "Lower Traps": 0.15,
            "Upper Back": 0.2, "Middle Back": 0.15, "Lower Back": 0.35,
            "Lats": 0.15, "Pectorals": 0.0, "Obliques": 0.25, "Abs": 0.35,
            "Glutes": 0.35, "Adductors": 0.15, "Abductors": 0.15,
            "Quads": 0.2, "Hamstrings": 0.25, "Shins": 0.05, "Calves": 0.15,
            "Hands/Grip": 0.4,
        },
        "tags": ["oly"],
        "equipment": ["kettlebell"],
        "biomechanics": {
            "implement_type": "kettlebell",
            "body_position": "standing",
            "laterality": "unilateral",
            "resistance_origin": "gravity",
            "resistance_direction": "vertical",
            "grip_style": "overhand",
            "bench_angle": None,
            "stability_demand": 0.75,
            "stretch_bias": 0.5,
            "shortened_bias": 0.25,
            "convergence_arc": None,
            "humeral_plane": None,
            "elbow_path": None,
            "movement_family": "olympic",
            "pattern_class": "ballistic",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Turkish Get-Up": {
        "activation": {
            "Forearms": 2, "Biceps": 1, "Triceps": 3, "Deltoids": 4,
            "Front/Anterior Delt": 4, "Rear/Posterior Delt": 2,
            "Side/Lateral Delt": 3, "Neck": 2, "Traps": 3,
            "Upper Traps": 3, "Mid Traps": 3, "Lower Traps": 2,
            "Upper Back": 3, "Middle Back": 2, "Lower Back": 3,
            "Lats": 2, "Pectorals": 1, "Obliques": 4, "Abs": 4,
            "Glutes": 4, "Adductors": 2, "Abductors": 3,
            "Quads": 3, "Hamstrings": 3, "Shins": 1, "Calves": 2,
            "Hands/Grip": 3,
        },
        "role_weighted": {
            "Forearms": 0.15, "Biceps": 0.06, "Triceps": 0.25, "Deltoids": 0.6,
            "Front/Anterior Delt": 0.6, "Rear/Posterior Delt": 0.15,
            "Side/Lateral Delt": 0.3, "Neck": 0.1, "Traps": 0.25,
            "Upper Traps": 0.25, "Mid Traps": 0.25, "Lower Traps": 0.15,
            "Upper Back": 0.25, "Middle Back": 0.15, "Lower Back": 0.3,
            "Lats": 0.15, "Pectorals": 0.06, "Obliques": 0.6, "Abs": 0.6,
            "Glutes": 0.7, "Adductors": 0.15, "Abductors": 0.25,
            "Quads": 0.3, "Hamstrings": 0.25, "Shins": 0.06, "Calves": 0.15,
            "Hands/Grip": 0.25,
        },
        "bottleneck": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 0.15, "Deltoids": 0.4,
            "Front/Anterior Delt": 0.4, "Rear/Posterior Delt": 0.1,
            "Side/Lateral Delt": 0.2, "Neck": 0.05, "Traps": 0.15,
            "Upper Traps": 0.15, "Mid Traps": 0.15, "Lower Traps": 0.1,
            "Upper Back": 0.15, "Middle Back": 0.1, "Lower Back": 0.2,
            "Lats": 0.1, "Pectorals": 0.0, "Obliques": 0.45, "Abs": 0.45,
            "Glutes": 0.5, "Adductors": 0.1, "Abductors": 0.15,
            "Quads": 0.2, "Hamstrings": 0.15, "Shins": 0.0, "Calves": 0.1,
            "Hands/Grip": 0.2,
        },
        "stabilization": {
            "Forearms": 0.2, "Biceps": 0.1, "Triceps": 0.2, "Deltoids": 0.4,
            "Front/Anterior Delt": 0.4, "Rear/Posterior Delt": 0.2,
            "Side/Lateral Delt": 0.3, "Neck": 0.1, "Traps": 0.25,
            "Upper Traps": 0.25, "Mid Traps": 0.25, "Lower Traps": 0.2,
            "Upper Back": 0.25, "Middle Back": 0.2, "Lower Back": 0.3,
            "Lats": 0.2, "Pectorals": 0.1, "Obliques": 0.4, "Abs": 0.4,
            "Glutes": 0.35, "Adductors": 0.15, "Abductors": 0.25,
            "Quads": 0.2, "Hamstrings": 0.2, "Shins": 0.05, "Calves": 0.15,
            "Hands/Grip": 0.3,
        },
        "tags": ["carry"],
        "equipment": ["kettlebell"],
        "biomechanics": {
            "implement_type": "kettlebell",
            "body_position": "supine",
            "laterality": "unilateral",
            "resistance_origin": "gravity",
            "resistance_direction": "vertical",
            "grip_style": "neutral",
            "bench_angle": None,
            "stability_demand": 0.85,
            "stretch_bias": None,
            "shortened_bias": None,
            "convergence_arc": None,
            "humeral_plane": None,
            "elbow_path": None,
            "movement_family": "complex",
            "pattern_class": "compound",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
}
