"""
Batch 2A Expansion — 10 High-Value Lower-Complexity Isolation & Band Exercises
Real authored activation matrices for all 27 muscles.
Activation scale: 0 (none) to 5 (maximal).

Muscles (by ID):
 1 Forearms, 2 Biceps, 3 Triceps, 4 Deltoids, 5 Front/Anterior Delt,
 6 Rear/Posterior Delt, 7 Side/Lateral Delt, 8 Neck, 9 Traps,
10 Upper Traps, 11 Mid Traps, 12 Lower Traps, 13 Upper Back,
14 Middle Back, 15 Lower Back, 16 Lats, 17 Pectorals, 18 Obliques,
19 Abs, 20 Glutes, 21 Adductors, 22 Abductors, 23 Quads,
24 Hamstrings, 25 Shins, 26 Calves, 27 Hands/Grip
"""

BATCH2A_EXERCISES = {
    "Dumbbell Front Raise": {
        "activation": {
            "Forearms": 1, "Biceps": 1, "Triceps": 0, "Deltoids": 4,
            "Front/Anterior Delt": 5, "Rear/Posterior Delt": 0,
            "Side/Lateral Delt": 2, "Neck": 1, "Traps": 2,
            "Upper Traps": 2, "Mid Traps": 1, "Lower Traps": 0,
            "Upper Back": 0, "Middle Back": 0, "Lower Back": 0,
            "Lats": 0, "Pectorals": 1, "Obliques": 0, "Abs": 1,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.1, "Biceps": 0.08, "Triceps": 0.0, "Deltoids": 0.7,
            "Front/Anterior Delt": 1.0, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.2, "Neck": 0.05, "Traps": 0.15,
            "Upper Traps": 0.2, "Mid Traps": 0.08, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.08, "Obliques": 0.0, "Abs": 0.05,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.15,
        },
        "bottleneck": {
            "Forearms": 0.1, "Biceps": 0.05, "Triceps": 0.0, "Deltoids": 0.5,
            "Front/Anterior Delt": 1.0, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.1, "Neck": 0.0, "Traps": 0.1,
            "Upper Traps": 0.1, "Mid Traps": 0.05, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.05, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.1,
        },
        "stabilization": {
            "Forearms": 0.15, "Biceps": 0.05, "Triceps": 0.0, "Deltoids": 0.3,
            "Front/Anterior Delt": 0.3, "Rear/Posterior Delt": 0.1,
            "Side/Lateral Delt": 0.15, "Neck": 0.05, "Traps": 0.15,
            "Upper Traps": 0.15, "Mid Traps": 0.1, "Lower Traps": 0.05,
            "Upper Back": 0.05, "Middle Back": 0.0, "Lower Back": 0.1,
            "Lats": 0.0, "Pectorals": 0.05, "Obliques": 0.1, "Abs": 0.15,
            "Glutes": 0.05, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.05, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.05,
            "Hands/Grip": 0.15,
        },
        "tags": ["push"],
        "equipment": ["dumbbell"],
        "biomechanics": {
            "implement_type": "dumbbell",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "gravity",
            "resistance_direction": "vertical",
            "grip_style": "overhand",
            "bench_angle": None,
            "stability_demand": 0.35,
            "stretch_bias": None,
            "shortened_bias": 0.6,
            "convergence_arc": None,
            "humeral_plane": "sagittal",
            "elbow_path": "fixed",
            "movement_family": "raise",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Dumbbell Overhead Tricep Extension": {
        "activation": {
            "Forearms": 1, "Biceps": 0, "Triceps": 5, "Deltoids": 1,
            "Front/Anterior Delt": 1, "Rear/Posterior Delt": 0,
            "Side/Lateral Delt": 0, "Neck": 0, "Traps": 1,
            "Upper Traps": 1, "Mid Traps": 0, "Lower Traps": 0,
            "Upper Back": 0, "Middle Back": 0, "Lower Back": 0,
            "Lats": 1, "Pectorals": 0, "Obliques": 0, "Abs": 1,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 1.0, "Deltoids": 0.08,
            "Front/Anterior Delt": 0.08, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.06,
            "Upper Traps": 0.06, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.08, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.08,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.15,
        },
        "bottleneck": {
            "Forearms": 0.05, "Biceps": 0.0, "Triceps": 1.0, "Deltoids": 0.05,
            "Front/Anterior Delt": 0.05, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.05, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.1,
        },
        "stabilization": {
            "Forearms": 0.15, "Biceps": 0.05, "Triceps": 0.2, "Deltoids": 0.15,
            "Front/Anterior Delt": 0.15, "Rear/Posterior Delt": 0.05,
            "Side/Lateral Delt": 0.05, "Neck": 0.05, "Traps": 0.1,
            "Upper Traps": 0.1, "Mid Traps": 0.05, "Lower Traps": 0.05,
            "Upper Back": 0.05, "Middle Back": 0.0, "Lower Back": 0.1,
            "Lats": 0.1, "Pectorals": 0.0, "Obliques": 0.1, "Abs": 0.15,
            "Glutes": 0.05, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "tags": ["push"],
        "equipment": ["dumbbell"],
        "biomechanics": {
            "implement_type": "dumbbell",
            "body_position": "seated",
            "laterality": "bilateral",
            "resistance_origin": "gravity",
            "resistance_direction": "vertical",
            "grip_style": "neutral",
            "bench_angle": 90.0,
            "stability_demand": 0.4,
            "stretch_bias": 0.7,
            "shortened_bias": 0.3,
            "convergence_arc": None,
            "humeral_plane": "sagittal",
            "elbow_path": "fixed",
            "movement_family": "extension",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Dumbbell Fly": {
        "activation": {
            "Forearms": 1, "Biceps": 1, "Triceps": 0, "Deltoids": 2,
            "Front/Anterior Delt": 3, "Rear/Posterior Delt": 0,
            "Side/Lateral Delt": 1, "Neck": 0, "Traps": 0,
            "Upper Traps": 0, "Mid Traps": 0, "Lower Traps": 0,
            "Upper Back": 0, "Middle Back": 0, "Lower Back": 0,
            "Lats": 0, "Pectorals": 5, "Obliques": 0, "Abs": 0,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.08, "Biceps": 0.08, "Triceps": 0.0, "Deltoids": 0.2,
            "Front/Anterior Delt": 0.3, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.08, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 1.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.15,
        },
        "bottleneck": {
            "Forearms": 0.05, "Biceps": 0.05, "Triceps": 0.0, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.15, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.05, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 1.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.1,
        },
        "stabilization": {
            "Forearms": 0.1, "Biceps": 0.15, "Triceps": 0.05, "Deltoids": 0.25,
            "Front/Anterior Delt": 0.25, "Rear/Posterior Delt": 0.1,
            "Side/Lateral Delt": 0.1, "Neck": 0.0, "Traps": 0.05,
            "Upper Traps": 0.05, "Mid Traps": 0.05, "Lower Traps": 0.05,
            "Upper Back": 0.05, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.05, "Pectorals": 0.3, "Obliques": 0.0, "Abs": 0.05,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.15,
        },
        "tags": ["push"],
        "equipment": ["dumbbell", "flat_bench"],
        "biomechanics": {
            "implement_type": "dumbbell",
            "body_position": "supine",
            "laterality": "bilateral",
            "resistance_origin": "gravity",
            "resistance_direction": "vertical",
            "grip_style": "neutral",
            "bench_angle": 0.0,
            "stability_demand": 0.45,
            "stretch_bias": 0.8,
            "shortened_bias": 0.3,
            "convergence_arc": 1,
            "humeral_plane": "transverse",
            "elbow_path": "fixed",
            "movement_family": "fly",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Incline Dumbbell Fly": {
        "activation": {
            "Forearms": 1, "Biceps": 1, "Triceps": 0, "Deltoids": 3,
            "Front/Anterior Delt": 3, "Rear/Posterior Delt": 0,
            "Side/Lateral Delt": 1, "Neck": 0, "Traps": 0,
            "Upper Traps": 0, "Mid Traps": 0, "Lower Traps": 0,
            "Upper Back": 0, "Middle Back": 0, "Lower Back": 0,
            "Lats": 0, "Pectorals": 5, "Obliques": 0, "Abs": 0,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.08, "Biceps": 0.08, "Triceps": 0.0, "Deltoids": 0.3,
            "Front/Anterior Delt": 0.35, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.08, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 1.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.15,
        },
        "bottleneck": {
            "Forearms": 0.05, "Biceps": 0.05, "Triceps": 0.0, "Deltoids": 0.15,
            "Front/Anterior Delt": 0.2, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.05, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 1.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.1,
        },
        "stabilization": {
            "Forearms": 0.1, "Biceps": 0.15, "Triceps": 0.05, "Deltoids": 0.3,
            "Front/Anterior Delt": 0.3, "Rear/Posterior Delt": 0.1,
            "Side/Lateral Delt": 0.1, "Neck": 0.0, "Traps": 0.05,
            "Upper Traps": 0.05, "Mid Traps": 0.05, "Lower Traps": 0.05,
            "Upper Back": 0.05, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.05, "Pectorals": 0.3, "Obliques": 0.0, "Abs": 0.05,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.15,
        },
        "tags": ["push"],
        "equipment": ["dumbbell", "adjustable_bench"],
        "biomechanics": {
            "implement_type": "dumbbell",
            "body_position": "incline",
            "laterality": "bilateral",
            "resistance_origin": "gravity",
            "resistance_direction": "vertical",
            "grip_style": "neutral",
            "bench_angle": 30.0,
            "stability_demand": 0.5,
            "stretch_bias": 0.85,
            "shortened_bias": 0.25,
            "convergence_arc": 1,
            "humeral_plane": "scapular",
            "elbow_path": "fixed",
            "movement_family": "fly",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Dumbbell Shrug": {
        "activation": {
            "Forearms": 2, "Biceps": 0, "Triceps": 0, "Deltoids": 1,
            "Front/Anterior Delt": 0, "Rear/Posterior Delt": 0,
            "Side/Lateral Delt": 0, "Neck": 2, "Traps": 5,
            "Upper Traps": 5, "Mid Traps": 2, "Lower Traps": 1,
            "Upper Back": 1, "Middle Back": 1, "Lower Back": 0,
            "Lats": 0, "Pectorals": 0, "Obliques": 0, "Abs": 0,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 3,
        },
        "role_weighted": {
            "Forearms": 0.15, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.08,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.15, "Traps": 0.9,
            "Upper Traps": 1.0, "Mid Traps": 0.2, "Lower Traps": 0.08,
            "Upper Back": 0.08, "Middle Back": 0.06, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.3,
        },
        "bottleneck": {
            "Forearms": 0.15, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.0,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.05, "Traps": 0.8,
            "Upper Traps": 1.0, "Mid Traps": 0.1, "Lower Traps": 0.05,
            "Upper Back": 0.05, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.25,
        },
        "stabilization": {
            "Forearms": 0.2, "Biceps": 0.05, "Triceps": 0.0, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.05, "Rear/Posterior Delt": 0.05,
            "Side/Lateral Delt": 0.05, "Neck": 0.1, "Traps": 0.3,
            "Upper Traps": 0.3, "Mid Traps": 0.15, "Lower Traps": 0.1,
            "Upper Back": 0.1, "Middle Back": 0.05, "Lower Back": 0.1,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.05, "Abs": 0.1,
            "Glutes": 0.05, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.05, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.05,
            "Hands/Grip": 0.35,
        },
        "tags": ["pull"],
        "equipment": ["dumbbell"],
        "biomechanics": {
            "implement_type": "dumbbell",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "gravity",
            "resistance_direction": "vertical",
            "grip_style": "neutral",
            "bench_angle": None,
            "stability_demand": 0.25,
            "stretch_bias": 0.5,
            "shortened_bias": 0.6,
            "convergence_arc": None,
            "humeral_plane": None,
            "elbow_path": None,
            "movement_family": "raise",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Cable Curl": {
        "activation": {
            "Forearms": 2, "Biceps": 5, "Triceps": 0, "Deltoids": 1,
            "Front/Anterior Delt": 1, "Rear/Posterior Delt": 0,
            "Side/Lateral Delt": 0, "Neck": 0, "Traps": 0,
            "Upper Traps": 0, "Mid Traps": 0, "Lower Traps": 0,
            "Upper Back": 0, "Middle Back": 0, "Lower Back": 0,
            "Lats": 0, "Pectorals": 0, "Obliques": 0, "Abs": 1,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 3,
        },
        "role_weighted": {
            "Forearms": 0.2, "Biceps": 1.0, "Triceps": 0.0, "Deltoids": 0.08,
            "Front/Anterior Delt": 0.08, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.06,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.25,
        },
        "bottleneck": {
            "Forearms": 0.15, "Biceps": 1.0, "Triceps": 0.0, "Deltoids": 0.0,
            "Front/Anterior Delt": 0.05, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "stabilization": {
            "Forearms": 0.15, "Biceps": 0.15, "Triceps": 0.0, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.1, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.05,
            "Upper Traps": 0.05, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.05,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.05, "Abs": 0.1,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "tags": ["pull"],
        "equipment": ["cable_machine"],
        "biomechanics": {
            "implement_type": "cable",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "low",
            "resistance_direction": "diagonal_low_high",
            "grip_style": "underhand",
            "bench_angle": None,
            "stability_demand": 0.3,
            "stretch_bias": 0.5,
            "shortened_bias": 0.6,
            "convergence_arc": None,
            "humeral_plane": "sagittal",
            "elbow_path": "fixed",
            "movement_family": "curl",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Cable Overhead Tricep Extension": {
        "activation": {
            "Forearms": 1, "Biceps": 0, "Triceps": 5, "Deltoids": 1,
            "Front/Anterior Delt": 1, "Rear/Posterior Delt": 0,
            "Side/Lateral Delt": 0, "Neck": 0, "Traps": 1,
            "Upper Traps": 1, "Mid Traps": 0, "Lower Traps": 0,
            "Upper Back": 0, "Middle Back": 0, "Lower Back": 0,
            "Lats": 1, "Pectorals": 0, "Obliques": 0, "Abs": 1,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 1.0, "Deltoids": 0.06,
            "Front/Anterior Delt": 0.06, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.06,
            "Upper Traps": 0.06, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.06, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.08,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.15,
        },
        "bottleneck": {
            "Forearms": 0.05, "Biceps": 0.0, "Triceps": 1.0, "Deltoids": 0.05,
            "Front/Anterior Delt": 0.05, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.05, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.1,
        },
        "stabilization": {
            "Forearms": 0.15, "Biceps": 0.05, "Triceps": 0.15, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.1, "Rear/Posterior Delt": 0.05,
            "Side/Lateral Delt": 0.05, "Neck": 0.0, "Traps": 0.1,
            "Upper Traps": 0.1, "Mid Traps": 0.05, "Lower Traps": 0.05,
            "Upper Back": 0.05, "Middle Back": 0.0, "Lower Back": 0.1,
            "Lats": 0.08, "Pectorals": 0.0, "Obliques": 0.1, "Abs": 0.15,
            "Glutes": 0.05, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.15,
        },
        "tags": ["push"],
        "equipment": ["cable_machine", "rope_attachment"],
        "biomechanics": {
            "implement_type": "cable",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "high",
            "resistance_direction": "diagonal_high_low",
            "grip_style": "rope",
            "bench_angle": None,
            "stability_demand": 0.35,
            "stretch_bias": 0.7,
            "shortened_bias": 0.4,
            "convergence_arc": None,
            "humeral_plane": "sagittal",
            "elbow_path": "fixed",
            "movement_family": "extension",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Band Pull-Apart": {
        "activation": {
            "Forearms": 1, "Biceps": 1, "Triceps": 0, "Deltoids": 3,
            "Front/Anterior Delt": 0, "Rear/Posterior Delt": 4,
            "Side/Lateral Delt": 2, "Neck": 1, "Traps": 3,
            "Upper Traps": 2, "Mid Traps": 4, "Lower Traps": 3,
            "Upper Back": 3, "Middle Back": 2, "Lower Back": 0,
            "Lats": 1, "Pectorals": 0, "Obliques": 0, "Abs": 0,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 1,
        },
        "role_weighted": {
            "Forearms": 0.08, "Biceps": 0.06, "Triceps": 0.0, "Deltoids": 0.3,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 0.7,
            "Side/Lateral Delt": 0.15, "Neck": 0.05, "Traps": 0.3,
            "Upper Traps": 0.2, "Mid Traps": 0.6, "Lower Traps": 0.35,
            "Upper Back": 0.35, "Middle Back": 0.2, "Lower Back": 0.0,
            "Lats": 0.08, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.08,
        },
        "bottleneck": {
            "Forearms": 0.05, "Biceps": 0.05, "Triceps": 0.0, "Deltoids": 0.15,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 0.6,
            "Side/Lateral Delt": 0.1, "Neck": 0.0, "Traps": 0.2,
            "Upper Traps": 0.1, "Mid Traps": 0.5, "Lower Traps": 0.3,
            "Upper Back": 0.25, "Middle Back": 0.15, "Lower Back": 0.0,
            "Lats": 0.05, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.05,
        },
        "stabilization": {
            "Forearms": 0.1, "Biceps": 0.1, "Triceps": 0.05, "Deltoids": 0.2,
            "Front/Anterior Delt": 0.1, "Rear/Posterior Delt": 0.2,
            "Side/Lateral Delt": 0.15, "Neck": 0.05, "Traps": 0.15,
            "Upper Traps": 0.1, "Mid Traps": 0.2, "Lower Traps": 0.15,
            "Upper Back": 0.15, "Middle Back": 0.1, "Lower Back": 0.05,
            "Lats": 0.1, "Pectorals": 0.05, "Obliques": 0.05, "Abs": 0.1,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.1,
        },
        "tags": ["pull"],
        "equipment": ["band"],
        "biomechanics": {
            "implement_type": "band",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "elastic",
            "resistance_direction": "horizontal",
            "grip_style": "overhand",
            "bench_angle": None,
            "stability_demand": 0.2,
            "stretch_bias": None,
            "shortened_bias": 0.8,
            "convergence_arc": None,
            "humeral_plane": "transverse",
            "elbow_path": "fixed",
            "movement_family": "row",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Band Face Pull": {
        "activation": {
            "Forearms": 1, "Biceps": 2, "Triceps": 0, "Deltoids": 3,
            "Front/Anterior Delt": 0, "Rear/Posterior Delt": 4,
            "Side/Lateral Delt": 2, "Neck": 1, "Traps": 3,
            "Upper Traps": 2, "Mid Traps": 3, "Lower Traps": 2,
            "Upper Back": 3, "Middle Back": 2, "Lower Back": 0,
            "Lats": 1, "Pectorals": 0, "Obliques": 0, "Abs": 0,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.1, "Biceps": 0.15, "Triceps": 0.0, "Deltoids": 0.3,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 0.65,
            "Side/Lateral Delt": 0.15, "Neck": 0.05, "Traps": 0.3,
            "Upper Traps": 0.2, "Mid Traps": 0.35, "Lower Traps": 0.2,
            "Upper Back": 0.35, "Middle Back": 0.2, "Lower Back": 0.0,
            "Lats": 0.08, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.15,
        },
        "bottleneck": {
            "Forearms": 0.05, "Biceps": 0.1, "Triceps": 0.0, "Deltoids": 0.15,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 0.55,
            "Side/Lateral Delt": 0.1, "Neck": 0.0, "Traps": 0.2,
            "Upper Traps": 0.1, "Mid Traps": 0.3, "Lower Traps": 0.15,
            "Upper Back": 0.25, "Middle Back": 0.15, "Lower Back": 0.0,
            "Lats": 0.05, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.1,
        },
        "stabilization": {
            "Forearms": 0.1, "Biceps": 0.15, "Triceps": 0.05, "Deltoids": 0.2,
            "Front/Anterior Delt": 0.1, "Rear/Posterior Delt": 0.2,
            "Side/Lateral Delt": 0.15, "Neck": 0.05, "Traps": 0.15,
            "Upper Traps": 0.1, "Mid Traps": 0.15, "Lower Traps": 0.1,
            "Upper Back": 0.15, "Middle Back": 0.1, "Lower Back": 0.05,
            "Lats": 0.1, "Pectorals": 0.0, "Obliques": 0.05, "Abs": 0.1,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.15,
        },
        "tags": ["pull"],
        "equipment": ["band"],
        "biomechanics": {
            "implement_type": "band",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "elastic",
            "resistance_direction": "horizontal",
            "grip_style": "overhand",
            "bench_angle": None,
            "stability_demand": 0.2,
            "stretch_bias": None,
            "shortened_bias": 0.75,
            "convergence_arc": None,
            "humeral_plane": "transverse",
            "elbow_path": "free",
            "movement_family": "pull",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Band Lateral Raise": {
        "activation": {
            "Forearms": 1, "Biceps": 0, "Triceps": 0, "Deltoids": 4,
            "Front/Anterior Delt": 1, "Rear/Posterior Delt": 1,
            "Side/Lateral Delt": 5, "Neck": 1, "Traps": 2,
            "Upper Traps": 3, "Mid Traps": 1, "Lower Traps": 1,
            "Upper Back": 0, "Middle Back": 0, "Lower Back": 0,
            "Lats": 0, "Pectorals": 0, "Obliques": 0, "Abs": 0,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 1,
        },
        "role_weighted": {
            "Forearms": 0.08, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.7,
            "Front/Anterior Delt": 0.1, "Rear/Posterior Delt": 0.1,
            "Side/Lateral Delt": 1.0, "Neck": 0.05, "Traps": 0.2,
            "Upper Traps": 0.3, "Mid Traps": 0.08, "Lower Traps": 0.05,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.08,
        },
        "bottleneck": {
            "Forearms": 0.08, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.5,
            "Front/Anterior Delt": 0.05, "Rear/Posterior Delt": 0.05,
            "Side/Lateral Delt": 1.0, "Neck": 0.0, "Traps": 0.1,
            "Upper Traps": 0.15, "Mid Traps": 0.05, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.05,
        },
        "stabilization": {
            "Forearms": 0.1, "Biceps": 0.05, "Triceps": 0.0, "Deltoids": 0.25,
            "Front/Anterior Delt": 0.1, "Rear/Posterior Delt": 0.1,
            "Side/Lateral Delt": 0.25, "Neck": 0.05, "Traps": 0.15,
            "Upper Traps": 0.15, "Mid Traps": 0.1, "Lower Traps": 0.05,
            "Upper Back": 0.05, "Middle Back": 0.0, "Lower Back": 0.05,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.05, "Abs": 0.1,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.08,
        },
        "tags": ["push"],
        "equipment": ["band"],
        "biomechanics": {
            "implement_type": "band",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "elastic",
            "resistance_direction": "vertical",
            "grip_style": "handle",
            "bench_angle": None,
            "stability_demand": 0.2,
            "stretch_bias": None,
            "shortened_bias": 0.7,
            "convergence_arc": None,
            "humeral_plane": "frontal",
            "elbow_path": "fixed",
            "movement_family": "raise",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
}
