"""
Batch 1 Expansion — 10 Dumbbell/Cable Isolation Exercises
Real authored activation matrices for all 27 muscles.
Activation scale: 0 (none) to 5 (maximal).

Muscles (by ID):
 1 Forearms, 2 Biceps, 3 Triceps, 4 Deltoids, 5 Front/Anterior Delt,
 6 Rear/Posterior Delt, 7 Side/Lateral Delt, 8 Neck, 9 Traps,
10 Upper Traps, 11 Mid Traps, 12 Lower Traps, 13 Upper Back,
14 Middle Back, 15 Lower Back, 16 Lats, 17 Pectorals, 18 Obliques,
19 Abs, 20 Glutes, 21 Adductors, 22 Abductors, 23 Quads,
24 Hamstrings, 25 Shins, 26 Calves, 27 Hands/Grip
"""

BATCH1_EXERCISES = {
    "Dumbbell Lateral Raise": {
        "activation": {
            "Forearms": 1, "Biceps": 0, "Triceps": 0, "Deltoids": 4,
            "Front/Anterior Delt": 1, "Rear/Posterior Delt": 1,
            "Side/Lateral Delt": 5, "Neck": 1, "Traps": 2,
            "Upper Traps": 3, "Mid Traps": 1, "Lower Traps": 1,
            "Upper Back": 0, "Middle Back": 0, "Lower Back": 0,
            "Lats": 0, "Pectorals": 0, "Obliques": 0, "Abs": 0,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.7,
            "Front/Anterior Delt": 0.1, "Rear/Posterior Delt": 0.1,
            "Side/Lateral Delt": 1.0, "Neck": 0.06, "Traps": 0.2,
            "Upper Traps": 0.3, "Mid Traps": 0.1, "Lower Traps": 0.06,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "bottleneck": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.5,
            "Front/Anterior Delt": 0.05, "Rear/Posterior Delt": 0.05,
            "Side/Lateral Delt": 1.0, "Neck": 0.0, "Traps": 0.1,
            "Upper Traps": 0.15, "Mid Traps": 0.05, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.1,
        },
        "stabilization": {
            "Forearms": 0.3, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.2,
            "Front/Anterior Delt": 0.1, "Rear/Posterior Delt": 0.1,
            "Side/Lateral Delt": 0.0, "Neck": 0.1, "Traps": 0.2,
            "Upper Traps": 0.2, "Mid Traps": 0.1, "Lower Traps": 0.1,
            "Upper Back": 0.1, "Middle Back": 0.0, "Lower Back": 0.1,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.1, "Abs": 0.1,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "tags": ["push"],
        "equipment": ["dumbbell"],
        "biomechanics": {
            "implement_type": "dumbbell",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "gravity",
            "resistance_direction": "vertical",
            "stability_demand": 0.5,
            "humeral_plane": "frontal",
            "elbow_path": "fixed",
            "movement_family": "raise",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Dumbbell Rear Delt Fly": {
        "activation": {
            "Forearms": 1, "Biceps": 0, "Triceps": 0, "Deltoids": 3,
            "Front/Anterior Delt": 0, "Rear/Posterior Delt": 5,
            "Side/Lateral Delt": 2, "Neck": 0, "Traps": 2,
            "Upper Traps": 1, "Mid Traps": 3, "Lower Traps": 2,
            "Upper Back": 2, "Middle Back": 2, "Lower Back": 1,
            "Lats": 0, "Pectorals": 0, "Obliques": 0, "Abs": 0,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.4,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 1.0,
            "Side/Lateral Delt": 0.2, "Neck": 0.0, "Traps": 0.2,
            "Upper Traps": 0.1, "Mid Traps": 0.3, "Lower Traps": 0.2,
            "Upper Back": 0.2, "Middle Back": 0.2, "Lower Back": 0.06,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "bottleneck": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.3,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 1.0,
            "Side/Lateral Delt": 0.1, "Neck": 0.0, "Traps": 0.1,
            "Upper Traps": 0.05, "Mid Traps": 0.15, "Lower Traps": 0.1,
            "Upper Back": 0.1, "Middle Back": 0.1, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.1,
        },
        "stabilization": {
            "Forearms": 0.2, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.1, "Neck": 0.0, "Traps": 0.1,
            "Upper Traps": 0.1, "Mid Traps": 0.1, "Lower Traps": 0.1,
            "Upper Back": 0.1, "Middle Back": 0.1, "Lower Back": 0.2,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.1, "Abs": 0.1,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "tags": ["push"],
        "equipment": ["dumbbell"],
        "biomechanics": {
            "implement_type": "dumbbell",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "gravity",
            "resistance_direction": "vertical",
            "stability_demand": 0.5,
            "humeral_plane": "transverse",
            "convergence_arc": 0,
            "movement_family": "fly",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Dumbbell Hammer Curl": {
        "activation": {
            "Forearms": 3, "Biceps": 4, "Triceps": 0, "Deltoids": 1,
            "Front/Anterior Delt": 1, "Rear/Posterior Delt": 0,
            "Side/Lateral Delt": 0, "Neck": 0, "Traps": 0,
            "Upper Traps": 0, "Mid Traps": 0, "Lower Traps": 0,
            "Upper Back": 0, "Middle Back": 0, "Lower Back": 0,
            "Lats": 0, "Pectorals": 0, "Obliques": 0, "Abs": 0,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 3,
        },
        "role_weighted": {
            "Forearms": 0.5, "Biceps": 1.0, "Triceps": 0.0, "Deltoids": 0.06,
            "Front/Anterior Delt": 0.06, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.4,
        },
        "bottleneck": {
            "Forearms": 0.3, "Biceps": 1.0, "Triceps": 0.0, "Deltoids": 0.0,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.3,
        },
        "stabilization": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.1, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.1,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.1, "Abs": 0.1,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.1,
        },
        "tags": ["pull"],
        "equipment": ["dumbbell"],
        "biomechanics": {
            "implement_type": "dumbbell",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "gravity",
            "resistance_direction": "vertical",
            "grip_style": "neutral",
            "stability_demand": 0.3,
            "humeral_plane": "sagittal",
            "elbow_path": "fixed",
            "movement_family": "curl",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Incline Dumbbell Curl": {
        "activation": {
            "Forearms": 2, "Biceps": 5, "Triceps": 0, "Deltoids": 1,
            "Front/Anterior Delt": 1, "Rear/Posterior Delt": 0,
            "Side/Lateral Delt": 0, "Neck": 0, "Traps": 0,
            "Upper Traps": 0, "Mid Traps": 0, "Lower Traps": 0,
            "Upper Back": 0, "Middle Back": 0, "Lower Back": 0,
            "Lats": 0, "Pectorals": 0, "Obliques": 0, "Abs": 0,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.3, "Biceps": 1.0, "Triceps": 0.0, "Deltoids": 0.06,
            "Front/Anterior Delt": 0.06, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "bottleneck": {
            "Forearms": 0.2, "Biceps": 1.0, "Triceps": 0.0, "Deltoids": 0.0,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "stabilization": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.1, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.1,
        },
        "tags": ["pull"],
        "equipment": ["dumbbell", "bench"],
        "biomechanics": {
            "implement_type": "dumbbell",
            "body_position": "incline",
            "laterality": "bilateral",
            "resistance_origin": "gravity",
            "resistance_direction": "vertical",
            "grip_style": "underhand",
            "bench_angle": 45.0,
            "stretch_bias": 0.8,
            "stability_demand": 0.3,
            "humeral_plane": "sagittal",
            "elbow_path": "fixed",
            "movement_family": "curl",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Cable Fly (low-to-high)": {
        "activation": {
            "Forearms": 1, "Biceps": 1, "Triceps": 0, "Deltoids": 2,
            "Front/Anterior Delt": 3, "Rear/Posterior Delt": 0,
            "Side/Lateral Delt": 1, "Neck": 0, "Traps": 0,
            "Upper Traps": 0, "Mid Traps": 0, "Lower Traps": 0,
            "Upper Back": 0, "Middle Back": 0, "Lower Back": 0,
            "Lats": 0, "Pectorals": 5, "Obliques": 1, "Abs": 1,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.1, "Biceps": 0.06, "Triceps": 0.0, "Deltoids": 0.2,
            "Front/Anterior Delt": 0.4, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.1, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 1.0, "Obliques": 0.06, "Abs": 0.06,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "bottleneck": {
            "Forearms": 0.05, "Biceps": 0.05, "Triceps": 0.0, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.2, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.05, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 1.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.05,
        },
        "stabilization": {
            "Forearms": 0.2, "Biceps": 0.1, "Triceps": 0.0, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.1, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.1, "Neck": 0.0, "Traps": 0.1,
            "Upper Traps": 0.0, "Mid Traps": 0.1, "Lower Traps": 0.0,
            "Upper Back": 0.1, "Middle Back": 0.0, "Lower Back": 0.1,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.2, "Abs": 0.2,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "tags": ["push"],
        "equipment": ["cable"],
        "biomechanics": {
            "implement_type": "cable",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "low",
            "resistance_direction": "diagonal_low_high",
            "grip_style": "handle",
            "stability_demand": 0.5,
            "convergence_arc": 1,
            "humeral_plane": "scapular",
            "movement_family": "fly",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Cable Fly (high-to-low)": {
        "activation": {
            "Forearms": 1, "Biceps": 1, "Triceps": 0, "Deltoids": 1,
            "Front/Anterior Delt": 2, "Rear/Posterior Delt": 0,
            "Side/Lateral Delt": 0, "Neck": 0, "Traps": 0,
            "Upper Traps": 0, "Mid Traps": 0, "Lower Traps": 0,
            "Upper Back": 0, "Middle Back": 0, "Lower Back": 0,
            "Lats": 0, "Pectorals": 5, "Obliques": 1, "Abs": 1,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.1, "Biceps": 0.06, "Triceps": 0.0, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.2, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 1.0, "Obliques": 0.06, "Abs": 0.06,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "bottleneck": {
            "Forearms": 0.05, "Biceps": 0.05, "Triceps": 0.0, "Deltoids": 0.05,
            "Front/Anterior Delt": 0.1, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 1.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.05,
        },
        "stabilization": {
            "Forearms": 0.2, "Biceps": 0.1, "Triceps": 0.0, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.1, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.1,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.2, "Abs": 0.2,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "tags": ["push"],
        "equipment": ["cable"],
        "biomechanics": {
            "implement_type": "cable",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "high",
            "resistance_direction": "diagonal_high_low",
            "grip_style": "handle",
            "stability_demand": 0.5,
            "convergence_arc": 1,
            "humeral_plane": "transverse",
            "movement_family": "fly",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Cable Tricep Pushdown": {
        "activation": {
            "Forearms": 1, "Biceps": 0, "Triceps": 5, "Deltoids": 0,
            "Front/Anterior Delt": 0, "Rear/Posterior Delt": 0,
            "Side/Lateral Delt": 0, "Neck": 0, "Traps": 0,
            "Upper Traps": 0, "Mid Traps": 0, "Lower Traps": 0,
            "Upper Back": 0, "Middle Back": 0, "Lower Back": 0,
            "Lats": 0, "Pectorals": 0, "Obliques": 0, "Abs": 1,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 1.0, "Deltoids": 0.0,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.06,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "bottleneck": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 1.0, "Deltoids": 0.0,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.1,
        },
        "stabilization": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.1, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.0, "Neck": 0.0, "Traps": 0.0,
            "Upper Traps": 0.0, "Mid Traps": 0.0, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.1,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.1, "Abs": 0.1,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.1,
        },
        "tags": ["push"],
        "equipment": ["cable"],
        "biomechanics": {
            "implement_type": "cable",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "high",
            "resistance_direction": "vertical",
            "grip_style": "rope",
            "shortened_bias": 0.7,
            "stability_demand": 0.3,
            "humeral_plane": "sagittal",
            "elbow_path": "fixed",
            "movement_family": "extension",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Cable Face Pull": {
        "activation": {
            "Forearms": 1, "Biceps": 1, "Triceps": 0, "Deltoids": 3,
            "Front/Anterior Delt": 0, "Rear/Posterior Delt": 5,
            "Side/Lateral Delt": 2, "Neck": 1, "Traps": 2,
            "Upper Traps": 1, "Mid Traps": 3, "Lower Traps": 2,
            "Upper Back": 2, "Middle Back": 1, "Lower Back": 0,
            "Lats": 0, "Pectorals": 0, "Obliques": 0, "Abs": 0,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.1, "Biceps": 0.06, "Triceps": 0.0, "Deltoids": 0.4,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 1.0,
            "Side/Lateral Delt": 0.2, "Neck": 0.06, "Traps": 0.2,
            "Upper Traps": 0.1, "Mid Traps": 0.3, "Lower Traps": 0.2,
            "Upper Back": 0.2, "Middle Back": 0.1, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "bottleneck": {
            "Forearms": 0.05, "Biceps": 0.05, "Triceps": 0.0, "Deltoids": 0.2,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 1.0,
            "Side/Lateral Delt": 0.1, "Neck": 0.0, "Traps": 0.1,
            "Upper Traps": 0.05, "Mid Traps": 0.15, "Lower Traps": 0.1,
            "Upper Back": 0.1, "Middle Back": 0.05, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.05,
        },
        "stabilization": {
            "Forearms": 0.2, "Biceps": 0.1, "Triceps": 0.0, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.1, "Neck": 0.0, "Traps": 0.1,
            "Upper Traps": 0.1, "Mid Traps": 0.1, "Lower Traps": 0.1,
            "Upper Back": 0.1, "Middle Back": 0.1, "Lower Back": 0.1,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.1, "Abs": 0.1,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "tags": ["pull"],
        "equipment": ["cable"],
        "biomechanics": {
            "implement_type": "cable",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "mid",
            "resistance_direction": "horizontal",
            "grip_style": "rope",
            "stability_demand": 0.4,
            "humeral_plane": "transverse",
            "movement_family": "pull",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Cable Lateral Raise": {
        "activation": {
            "Forearms": 1, "Biceps": 0, "Triceps": 0, "Deltoids": 4,
            "Front/Anterior Delt": 1, "Rear/Posterior Delt": 1,
            "Side/Lateral Delt": 5, "Neck": 1, "Traps": 2,
            "Upper Traps": 3, "Mid Traps": 1, "Lower Traps": 1,
            "Upper Back": 0, "Middle Back": 0, "Lower Back": 0,
            "Lats": 0, "Pectorals": 0, "Obliques": 1, "Abs": 0,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.7,
            "Front/Anterior Delt": 0.1, "Rear/Posterior Delt": 0.1,
            "Side/Lateral Delt": 1.0, "Neck": 0.06, "Traps": 0.2,
            "Upper Traps": 0.3, "Mid Traps": 0.1, "Lower Traps": 0.06,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.06, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "bottleneck": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.5,
            "Front/Anterior Delt": 0.05, "Rear/Posterior Delt": 0.05,
            "Side/Lateral Delt": 1.0, "Neck": 0.0, "Traps": 0.1,
            "Upper Traps": 0.15, "Mid Traps": 0.05, "Lower Traps": 0.0,
            "Upper Back": 0.0, "Middle Back": 0.0, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.1,
        },
        "stabilization": {
            "Forearms": 0.2, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.05, "Rear/Posterior Delt": 0.05,
            "Side/Lateral Delt": 0.0, "Neck": 0.1, "Traps": 0.1,
            "Upper Traps": 0.1, "Mid Traps": 0.1, "Lower Traps": 0.1,
            "Upper Back": 0.1, "Middle Back": 0.0, "Lower Back": 0.1,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.2, "Abs": 0.1,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "tags": ["push"],
        "equipment": ["cable"],
        "biomechanics": {
            "implement_type": "cable",
            "body_position": "standing",
            "laterality": "unilateral",
            "resistance_origin": "low",
            "resistance_direction": "diagonal_low_high",
            "grip_style": "handle",
            "stability_demand": 0.4,
            "humeral_plane": "frontal",
            "elbow_path": "fixed",
            "movement_family": "raise",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
    "Cable Rear Delt Fly": {
        "activation": {
            "Forearms": 1, "Biceps": 0, "Triceps": 0, "Deltoids": 3,
            "Front/Anterior Delt": 0, "Rear/Posterior Delt": 5,
            "Side/Lateral Delt": 2, "Neck": 0, "Traps": 2,
            "Upper Traps": 1, "Mid Traps": 3, "Lower Traps": 2,
            "Upper Back": 2, "Middle Back": 1, "Lower Back": 0,
            "Lats": 0, "Pectorals": 0, "Obliques": 0, "Abs": 0,
            "Glutes": 0, "Adductors": 0, "Abductors": 0,
            "Quads": 0, "Hamstrings": 0, "Shins": 0, "Calves": 0,
            "Hands/Grip": 2,
        },
        "role_weighted": {
            "Forearms": 0.1, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.4,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 1.0,
            "Side/Lateral Delt": 0.2, "Neck": 0.0, "Traps": 0.2,
            "Upper Traps": 0.1, "Mid Traps": 0.3, "Lower Traps": 0.2,
            "Upper Back": 0.2, "Middle Back": 0.1, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "bottleneck": {
            "Forearms": 0.05, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.2,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 1.0,
            "Side/Lateral Delt": 0.1, "Neck": 0.0, "Traps": 0.1,
            "Upper Traps": 0.05, "Mid Traps": 0.15, "Lower Traps": 0.1,
            "Upper Back": 0.1, "Middle Back": 0.05, "Lower Back": 0.0,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.0, "Abs": 0.0,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.05,
        },
        "stabilization": {
            "Forearms": 0.2, "Biceps": 0.0, "Triceps": 0.0, "Deltoids": 0.1,
            "Front/Anterior Delt": 0.0, "Rear/Posterior Delt": 0.0,
            "Side/Lateral Delt": 0.1, "Neck": 0.0, "Traps": 0.1,
            "Upper Traps": 0.1, "Mid Traps": 0.1, "Lower Traps": 0.1,
            "Upper Back": 0.1, "Middle Back": 0.1, "Lower Back": 0.1,
            "Lats": 0.0, "Pectorals": 0.0, "Obliques": 0.1, "Abs": 0.1,
            "Glutes": 0.0, "Adductors": 0.0, "Abductors": 0.0,
            "Quads": 0.0, "Hamstrings": 0.0, "Shins": 0.0, "Calves": 0.0,
            "Hands/Grip": 0.2,
        },
        "tags": ["pull"],
        "equipment": ["cable"],
        "biomechanics": {
            "implement_type": "cable",
            "body_position": "standing",
            "laterality": "bilateral",
            "resistance_origin": "mid",
            "resistance_direction": "horizontal",
            "grip_style": "handle",
            "stability_demand": 0.4,
            "convergence_arc": 0,
            "humeral_plane": "transverse",
            "movement_family": "fly",
            "pattern_class": "isolation",
            "biomechanics_version": 2,
            "metadata_tier": "full",
        },
    },
}
