BIOMECHANICS_DATA = {
    "Back Squat (high-bar)": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.6,
    },
    "Back Squat (low-bar)": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.6,
    },
    "Front Squat": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
    },
    "Box Squat": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.5,
    },
    "Pause Squat": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
    },
    "Overhead Squat": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.9,
    },
    "Zercher Squat": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
    },
    "Goblet Squat": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.5,
    },
    "Safety Bar Squat": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "neutral",
        "stability_demand": 0.5,
    },
    "Hack Squat": {
        "implement_type": "machine",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.2,
    },
    "Conventional Deadlift": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
    },
    "Sumo Deadlift": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
    },
    "Romanian Deadlift": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stretch_bias": 0.8,
        "stability_demand": 0.6,
    },
    "Stiff-Leg Deadlift": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stretch_bias": 0.9,
        "stability_demand": 0.6,
    },
    "Deficit Deadlift": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stretch_bias": 0.7,
        "stability_demand": 0.7,
    },
    "Block/Pin Pull Deadlift": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "shortened_bias": 0.7,
        "stability_demand": 0.5,
    },
    "Rack Pull": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "shortened_bias": 0.8,
        "stability_demand": 0.5,
    },
    "Trap-Bar Deadlift (high-handle)": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "neutral",
        "stability_demand": 0.5,
    },
    "Trap-Bar Deadlift (low-handle)": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "neutral",
        "stability_demand": 0.5,
    },
    "Single-Leg Romanian Deadlift": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "unilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stretch_bias": 0.8,
        "stability_demand": 0.9,
    },
    "Good Morning (barbell)": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stretch_bias": 0.7,
        "stability_demand": 0.6,
    },
    "Glute-Ham Raise": {
        "implement_type": "machine",
        "body_position": "prone",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stretch_bias": 0.7,
        "stability_demand": 0.4,
    },
    "Walking Lunge": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "alternating",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
    },
    "Reverse Lunge": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "alternating",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
    },
    "Forward Lunge": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "alternating",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
    },
    "Bulgarian Split Squat": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "unilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.8,
    },
    "Rear-Foot-Elevated Split Squat": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "unilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.8,
    },
    "Step-Up (high box, loaded)": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "unilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
    },
    "Single-Leg Squat / Pistol Squat": {
        "implement_type": "bodyweight",
        "body_position": "standing",
        "laterality": "unilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.9,
    },
    "Barbell Hip Thrust": {
        "implement_type": "barbell",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "shortened_bias": 0.8,
        "stability_demand": 0.3,
    },
    "Barbell Glute Bridge": {
        "implement_type": "barbell",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "shortened_bias": 0.7,
        "stability_demand": 0.3,
    },
    "Single-Leg Hip Thrust": {
        "implement_type": "bodyweight",
        "body_position": "supine",
        "laterality": "unilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "shortened_bias": 0.7,
        "stability_demand": 0.5,
    },
    "Flat Barbell Bench Press": {
        "implement_type": "barbell",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "bench_angle": 0.0,
        "humeral_plane": "transverse",
        "elbow_path": "tracking",
        "stability_demand": 0.4,
    },
    "Flat Dumbbell Bench Press": {
        "implement_type": "dumbbell",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "bench_angle": 0.0,
        "humeral_plane": "transverse",
        "elbow_path": "free",
        "convergence_arc": 1,
        "stability_demand": 0.6,
    },
    "Incline Barbell Bench Press": {
        "implement_type": "barbell",
        "body_position": "incline",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "bench_angle": 30.0,
        "humeral_plane": "scapular",
        "elbow_path": "tracking",
        "stability_demand": 0.4,
    },
    "Incline Dumbbell Bench Press": {
        "implement_type": "dumbbell",
        "body_position": "incline",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "bench_angle": 30.0,
        "humeral_plane": "scapular",
        "elbow_path": "free",
        "convergence_arc": 1,
        "stability_demand": 0.6,
    },
    "Decline Bench Press": {
        "implement_type": "barbell",
        "body_position": "decline",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "bench_angle": -15.0,
        "humeral_plane": "transverse",
        "elbow_path": "tracking",
        "stability_demand": 0.3,
    },
    "Close-Grip Bench Press": {
        "implement_type": "barbell",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "bench_angle": 0.0,
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "stability_demand": 0.4,
    },
    "Floor Press": {
        "implement_type": "barbell",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "bench_angle": 0.0,
        "shortened_bias": 0.6,
        "humeral_plane": "transverse",
        "elbow_path": "tracking",
        "stability_demand": 0.3,
    },
    "Board Press / Pin Press": {
        "implement_type": "barbell",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "bench_angle": 0.0,
        "shortened_bias": 0.8,
        "humeral_plane": "transverse",
        "elbow_path": "tracking",
        "stability_demand": 0.3,
    },
    "Spoto Press": {
        "implement_type": "barbell",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "bench_angle": 0.0,
        "humeral_plane": "transverse",
        "elbow_path": "tracking",
        "stability_demand": 0.5,
    },
    "Weighted Push-Up": {
        "implement_type": "bodyweight",
        "body_position": "prone",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "humeral_plane": "transverse",
        "stability_demand": 0.6,
    },
    "Parallel Bar Dips (chest-focused)": {
        "implement_type": "bodyweight",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "stretch_bias": 0.6,
        "stability_demand": 0.6,
    },
    "Parallel Bar Dips (tricep-focused)": {
        "implement_type": "bodyweight",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "humeral_plane": "sagittal",
        "elbow_path": "fixed",
        "stability_demand": 0.6,
    },
    "Ring Dips": {
        "implement_type": "bodyweight",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "humeral_plane": "sagittal",
        "stability_demand": 0.9,
    },
    "Standing Barbell Overhead Press": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "humeral_plane": "scapular",
        "elbow_path": "tracking",
        "stability_demand": 0.6,
    },
    "Standing Dumbbell Overhead Press": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "humeral_plane": "scapular",
        "elbow_path": "free",
        "stability_demand": 0.7,
    },
    "Seated Barbell Overhead Press": {
        "implement_type": "barbell",
        "body_position": "seated",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "humeral_plane": "scapular",
        "elbow_path": "tracking",
        "stability_demand": 0.4,
    },
    "Seated Dumbbell Overhead Press": {
        "implement_type": "dumbbell",
        "body_position": "seated",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "humeral_plane": "scapular",
        "elbow_path": "free",
        "stability_demand": 0.5,
    },
    "Push Press": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "humeral_plane": "scapular",
        "stability_demand": 0.6,
    },
    "Push Jerk": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "humeral_plane": "scapular",
        "stability_demand": 0.7,
    },
    "Split Jerk": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "humeral_plane": "scapular",
        "stability_demand": 0.8,
    },
    "Handstand Push-Up": {
        "implement_type": "bodyweight",
        "body_position": "inverted",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "humeral_plane": "scapular",
        "stability_demand": 0.9,
    },
    "Viking Press": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "diagonal_low_high",
        "grip_style": "neutral",
        "humeral_plane": "scapular",
        "stability_demand": 0.5,
    },
    "Bent-Over Barbell Row (overhand)": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "stability_demand": 0.6,
    },
    "Bent-Over Barbell Row (underhand)": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "underhand",
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "stability_demand": 0.6,
    },
    "Pendlay Row": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "stability_demand": 0.6,
    },
    "Yates Row": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "underhand",
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "stability_demand": 0.5,
    },
    "Chest-Supported Row": {
        "implement_type": "dumbbell",
        "body_position": "prone",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "humeral_plane": "sagittal",
        "elbow_path": "free",
        "stability_demand": 0.2,
    },
    "T-Bar Row": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "diagonal_low_high",
        "grip_style": "neutral",
        "humeral_plane": "sagittal",
        "stability_demand": 0.5,
    },
    "Meadows Row": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "unilateral",
        "resistance_origin": "floor",
        "resistance_direction": "diagonal_low_high",
        "grip_style": "overhand",
        "humeral_plane": "sagittal",
        "stability_demand": 0.6,
    },
    "Seated Cable Row": {
        "implement_type": "cable",
        "body_position": "seated",
        "laterality": "bilateral",
        "resistance_origin": "low",
        "resistance_direction": "horizontal",
        "grip_style": "neutral",
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "stability_demand": 0.3,
    },
    "Dumbbell Row": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "unilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "humeral_plane": "sagittal",
        "elbow_path": "free",
        "stability_demand": 0.5,
    },
    "Inverted Row": {
        "implement_type": "bodyweight",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "humeral_plane": "sagittal",
        "stability_demand": 0.5,
    },
    "Pull-Up (overhand grip)": {
        "implement_type": "bodyweight",
        "body_position": "hanging",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "humeral_plane": "frontal",
        "elbow_path": "tracking",
        "stability_demand": 0.6,
    },
    "Chin-Up (underhand grip)": {
        "implement_type": "bodyweight",
        "body_position": "hanging",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "underhand",
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "stability_demand": 0.6,
    },
    "Neutral-Grip Pull-Up": {
        "implement_type": "bodyweight",
        "body_position": "hanging",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "neutral",
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "stability_demand": 0.6,
    },
    "Weighted Pull-Up": {
        "implement_type": "bodyweight",
        "body_position": "hanging",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "humeral_plane": "frontal",
        "elbow_path": "tracking",
        "stability_demand": 0.6,
    },
    "Weighted Chin-Up": {
        "implement_type": "bodyweight",
        "body_position": "hanging",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "underhand",
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "stability_demand": 0.6,
    },
    "Commando Pull-Up": {
        "implement_type": "bodyweight",
        "body_position": "hanging",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "mixed",
        "humeral_plane": "sagittal",
        "stability_demand": 0.7,
    },
    "L-Sit Pull-Up": {
        "implement_type": "bodyweight",
        "body_position": "hanging",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "humeral_plane": "frontal",
        "stability_demand": 0.8,
    },
    "Muscle-Up": {
        "implement_type": "bodyweight",
        "body_position": "hanging",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "false",
        "humeral_plane": "frontal",
        "stability_demand": 0.9,
    },
    "Power Clean": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.8,
    },
    "Hang Power Clean": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.8,
    },
    "Clean Pull": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
    },
    "Clean and Jerk": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.9,
    },
    "Power Snatch": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.9,
    },
    "Hang Power Snatch": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.9,
    },
    "Snatch Pull": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
    },
    "Clean High Pull": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
    },
    "Barbell Complex": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
    },
    "Thruster": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
    },
    "Devil\u2019s Press": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
    },
    "Farmer\u2019s Walk": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.6,
    },
    "Suitcase Carry": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "unilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.8,
    },
    "Overhead Carry": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.8,
    },
    "Zercher Carry": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
    },
    "Yoke Walk": {
        "implement_type": "yoke",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
    },
    "Sandbag Carry": {
        "implement_type": "sandbag",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.8,
    },
    "Sled Push": {
        "implement_type": "sled",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "horizontal",
        "stability_demand": 0.5,
    },
    "Sled Pull": {
        "implement_type": "sled",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "horizontal",
        "stability_demand": 0.5,
    },
    "Tire Flip": {
        "implement_type": "tire",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
    },
}
