"""
Exercise Biomechanics Seed Data — Field-Authoring Spec v2

=== FIELD CLASSIFICATION ===

STRUCTURAL (safe for hard filtering by Expo):
  implement_type     REQUIRED  barbell|dumbbell|bodyweight|cable|machine|kettlebell|band|sled|sandbag|tire|yoke
  body_position      REQUIRED  standing|seated|supine|prone|incline|decline|hanging|inverted|kneeling|side_lying
  laterality         REQUIRED  bilateral|unilateral|alternating
  resistance_origin  REQUIRED  gravity|floor|low|mid|high|overhead|elastic
  resistance_direction REQUIRED  vertical|horizontal|diagonal_low_high|diagonal_high_low|rotational
  grip_style         NULLABLE  overhand|underhand|neutral|mixed|false|rope|handle — null when grip is not a defining characteristic
  bench_angle        NULLABLE  float degrees (0=flat, 30/45=incline, -15/-30=decline) — null when no bench used

INTERPRETIVE (display/advisory only, not for hard filtering):
  stretch_bias       NULLABLE  float 0-1 — only when resistance profile meaningfully peaks at stretched position. null for most exercises.
  shortened_bias     NULLABLE  float 0-1 — only when resistance profile meaningfully peaks at contraction. null for most exercises.
  stability_demand   REQUIRED  float 0-1 — always applicable
  convergence_arc    NULLABLE  0|1 — only for movements with real inward converging arm path (flies, DB presses). null for barbell/machine/lower body.
  humeral_plane      NULLABLE  sagittal|frontal|scapular|transverse — only for upper-body shoulder-driven patterns. null for lower body, carries, oly lifts.
  elbow_path         NULLABLE  fixed|free|tracking — only where elbow tracking materially defines the exercise. null for lower body, carries, whole-body.

CATEGORICAL (Expo filtering/display):
  movement_family    REQUIRED  press|row|fly|curl|extension|raise|squat|hinge|lunge|thrust|carry|pull|dip|olympic|complex|push
  pattern_class      REQUIRED  compound|isolation|carry|ballistic|olympic

VERSIONING:
  biomechanics_version  INTEGER  current = 2 (v1 = initial sparse pass, v2 = spec-driven enrichment)
  metadata_tier         TEXT     core|extended|full
                                 core = structural + stability_demand + movement_family + pattern_class
                                 extended = core + applicable interpretive fields
                                 full = all applicable fields authored with high confidence
"""

BIOMECHANICS_DATA = {
    "Back Squat (high-bar)": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.6,
        "movement_family": "squat",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Back Squat (low-bar)": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.6,
        "movement_family": "squat",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Front Squat": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
        "movement_family": "squat",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Box Squat": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.5,
        "movement_family": "squat",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Pause Squat": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stretch_bias": 0.7,
        "stability_demand": 0.7,
        "movement_family": "squat",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Overhead Squat": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.9,
        "humeral_plane": "frontal",
        "movement_family": "squat",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Zercher Squat": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
        "movement_family": "squat",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Goblet Squat": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.5,
        "movement_family": "squat",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Safety Bar Squat": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "neutral",
        "stability_demand": 0.5,
        "movement_family": "squat",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Hack Squat": {
        "implement_type": "machine",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.2,
        "movement_family": "squat",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Conventional Deadlift": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
        "movement_family": "hinge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Sumo Deadlift": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
        "movement_family": "hinge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Romanian Deadlift": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stretch_bias": 0.8,
        "stability_demand": 0.6,
        "movement_family": "hinge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Stiff-Leg Deadlift": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stretch_bias": 0.9,
        "stability_demand": 0.6,
        "movement_family": "hinge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Deficit Deadlift": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stretch_bias": 0.7,
        "stability_demand": 0.7,
        "movement_family": "hinge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Block/Pin Pull Deadlift": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "shortened_bias": 0.7,
        "stability_demand": 0.5,
        "movement_family": "hinge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Rack Pull": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "shortened_bias": 0.8,
        "stability_demand": 0.5,
        "movement_family": "hinge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Trap-Bar Deadlift (high-handle)": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "neutral",
        "stability_demand": 0.5,
        "movement_family": "hinge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Trap-Bar Deadlift (low-handle)": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "neutral",
        "stability_demand": 0.5,
        "movement_family": "hinge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Single-Leg Romanian Deadlift": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "unilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stretch_bias": 0.8,
        "stability_demand": 0.9,
        "movement_family": "hinge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Good Morning (barbell)": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stretch_bias": 0.7,
        "stability_demand": 0.6,
        "movement_family": "hinge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Glute-Ham Raise": {
        "implement_type": "machine",
        "body_position": "prone",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stretch_bias": 0.7,
        "stability_demand": 0.4,
        "movement_family": "hinge",
        "pattern_class": "isolation",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Walking Lunge": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "alternating",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
        "movement_family": "lunge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Reverse Lunge": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "alternating",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
        "movement_family": "lunge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Forward Lunge": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "alternating",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
        "movement_family": "lunge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Bulgarian Split Squat": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "unilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stretch_bias": 0.6,
        "stability_demand": 0.8,
        "movement_family": "lunge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Rear-Foot-Elevated Split Squat": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "unilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stretch_bias": 0.6,
        "stability_demand": 0.8,
        "movement_family": "lunge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Step-Up (high box, loaded)": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "unilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
        "movement_family": "lunge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Single-Leg Squat / Pistol Squat": {
        "implement_type": "bodyweight",
        "body_position": "standing",
        "laterality": "unilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.9,
        "movement_family": "squat",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Barbell Hip Thrust": {
        "implement_type": "barbell",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "shortened_bias": 0.8,
        "stability_demand": 0.3,
        "movement_family": "thrust",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Barbell Glute Bridge": {
        "implement_type": "barbell",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "shortened_bias": 0.7,
        "stability_demand": 0.3,
        "movement_family": "thrust",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Single-Leg Hip Thrust": {
        "implement_type": "bodyweight",
        "body_position": "supine",
        "laterality": "unilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "shortened_bias": 0.7,
        "stability_demand": 0.5,
        "movement_family": "thrust",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Flat Barbell Bench Press": {
        "implement_type": "barbell",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "bench_angle": 0.0,
        "stability_demand": 0.4,
        "humeral_plane": "transverse",
        "elbow_path": "tracking",
        "movement_family": "press",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Flat Dumbbell Bench Press": {
        "implement_type": "dumbbell",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "bench_angle": 0.0,
        "stability_demand": 0.6,
        "convergence_arc": 1,
        "humeral_plane": "transverse",
        "elbow_path": "free",
        "movement_family": "press",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Incline Barbell Bench Press": {
        "implement_type": "barbell",
        "body_position": "incline",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "bench_angle": 30.0,
        "stability_demand": 0.4,
        "humeral_plane": "scapular",
        "elbow_path": "tracking",
        "movement_family": "press",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Incline Dumbbell Bench Press": {
        "implement_type": "dumbbell",
        "body_position": "incline",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "bench_angle": 30.0,
        "stability_demand": 0.6,
        "convergence_arc": 1,
        "humeral_plane": "scapular",
        "elbow_path": "free",
        "movement_family": "press",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Decline Bench Press": {
        "implement_type": "barbell",
        "body_position": "decline",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "bench_angle": -15.0,
        "stability_demand": 0.3,
        "humeral_plane": "transverse",
        "elbow_path": "tracking",
        "movement_family": "press",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Close-Grip Bench Press": {
        "implement_type": "barbell",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "bench_angle": 0.0,
        "stability_demand": 0.4,
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "movement_family": "press",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Floor Press": {
        "implement_type": "barbell",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "bench_angle": 0.0,
        "shortened_bias": 0.6,
        "stability_demand": 0.3,
        "humeral_plane": "transverse",
        "elbow_path": "tracking",
        "movement_family": "press",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Board Press / Pin Press": {
        "implement_type": "barbell",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "bench_angle": 0.0,
        "shortened_bias": 0.8,
        "stability_demand": 0.3,
        "humeral_plane": "transverse",
        "elbow_path": "tracking",
        "movement_family": "press",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Spoto Press": {
        "implement_type": "barbell",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "bench_angle": 0.0,
        "stability_demand": 0.5,
        "humeral_plane": "transverse",
        "elbow_path": "tracking",
        "movement_family": "press",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Weighted Push-Up": {
        "implement_type": "bodyweight",
        "body_position": "prone",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.6,
        "humeral_plane": "transverse",
        "movement_family": "press",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Parallel Bar Dips (chest-focused)": {
        "implement_type": "bodyweight",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stretch_bias": 0.6,
        "stability_demand": 0.6,
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "movement_family": "dip",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Parallel Bar Dips (tricep-focused)": {
        "implement_type": "bodyweight",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.6,
        "humeral_plane": "sagittal",
        "elbow_path": "fixed",
        "movement_family": "dip",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Ring Dips": {
        "implement_type": "bodyweight",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.9,
        "humeral_plane": "sagittal",
        "movement_family": "dip",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Standing Barbell Overhead Press": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.6,
        "humeral_plane": "scapular",
        "elbow_path": "tracking",
        "movement_family": "press",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Standing Dumbbell Overhead Press": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
        "humeral_plane": "scapular",
        "elbow_path": "free",
        "movement_family": "press",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Seated Barbell Overhead Press": {
        "implement_type": "barbell",
        "body_position": "seated",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "bench_angle": 90.0,
        "stability_demand": 0.4,
        "humeral_plane": "scapular",
        "elbow_path": "tracking",
        "movement_family": "press",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Seated Dumbbell Overhead Press": {
        "implement_type": "dumbbell",
        "body_position": "seated",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "bench_angle": 90.0,
        "stability_demand": 0.5,
        "humeral_plane": "scapular",
        "elbow_path": "free",
        "movement_family": "press",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Push Press": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.6,
        "humeral_plane": "scapular",
        "movement_family": "press",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Push Jerk": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
        "humeral_plane": "scapular",
        "movement_family": "press",
        "pattern_class": "olympic",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Split Jerk": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.8,
        "humeral_plane": "scapular",
        "movement_family": "press",
        "pattern_class": "olympic",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Handstand Push-Up": {
        "implement_type": "bodyweight",
        "body_position": "inverted",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.9,
        "humeral_plane": "scapular",
        "movement_family": "press",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Viking Press": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "diagonal_low_high",
        "grip_style": "neutral",
        "stability_demand": 0.5,
        "humeral_plane": "scapular",
        "movement_family": "press",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Bent-Over Barbell Row (overhand)": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.6,
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "movement_family": "row",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Bent-Over Barbell Row (underhand)": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "underhand",
        "stability_demand": 0.6,
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "movement_family": "row",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Pendlay Row": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.6,
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "movement_family": "row",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Yates Row": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "underhand",
        "stability_demand": 0.5,
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "movement_family": "row",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Chest-Supported Row": {
        "implement_type": "dumbbell",
        "body_position": "prone",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.2,
        "humeral_plane": "sagittal",
        "elbow_path": "free",
        "movement_family": "row",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "T-Bar Row": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "diagonal_low_high",
        "grip_style": "neutral",
        "stability_demand": 0.5,
        "humeral_plane": "sagittal",
        "movement_family": "row",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Meadows Row": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "unilateral",
        "resistance_origin": "floor",
        "resistance_direction": "diagonal_low_high",
        "grip_style": "overhand",
        "stability_demand": 0.6,
        "humeral_plane": "sagittal",
        "movement_family": "row",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Seated Cable Row": {
        "implement_type": "cable",
        "body_position": "seated",
        "laterality": "bilateral",
        "resistance_origin": "low",
        "resistance_direction": "horizontal",
        "grip_style": "neutral",
        "stability_demand": 0.3,
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "movement_family": "row",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Dumbbell Row": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "unilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.5,
        "humeral_plane": "sagittal",
        "elbow_path": "free",
        "movement_family": "row",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Inverted Row": {
        "implement_type": "bodyweight",
        "body_position": "supine",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.5,
        "humeral_plane": "sagittal",
        "movement_family": "row",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Pull-Up (overhand grip)": {
        "implement_type": "bodyweight",
        "body_position": "hanging",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.6,
        "humeral_plane": "frontal",
        "elbow_path": "tracking",
        "movement_family": "pull",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Chin-Up (underhand grip)": {
        "implement_type": "bodyweight",
        "body_position": "hanging",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "underhand",
        "stability_demand": 0.6,
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "movement_family": "pull",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Neutral-Grip Pull-Up": {
        "implement_type": "bodyweight",
        "body_position": "hanging",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "neutral",
        "stability_demand": 0.6,
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "movement_family": "pull",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Weighted Pull-Up": {
        "implement_type": "bodyweight",
        "body_position": "hanging",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.6,
        "humeral_plane": "frontal",
        "elbow_path": "tracking",
        "movement_family": "pull",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Weighted Chin-Up": {
        "implement_type": "bodyweight",
        "body_position": "hanging",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "underhand",
        "stability_demand": 0.6,
        "humeral_plane": "sagittal",
        "elbow_path": "tracking",
        "movement_family": "pull",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Commando Pull-Up": {
        "implement_type": "bodyweight",
        "body_position": "hanging",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "mixed",
        "stability_demand": 0.7,
        "humeral_plane": "sagittal",
        "movement_family": "pull",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "L-Sit Pull-Up": {
        "implement_type": "bodyweight",
        "body_position": "hanging",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.8,
        "humeral_plane": "frontal",
        "elbow_path": "tracking",
        "movement_family": "pull",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Muscle-Up": {
        "implement_type": "bodyweight",
        "body_position": "hanging",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "false",
        "stability_demand": 0.9,
        "humeral_plane": "frontal",
        "movement_family": "pull",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Power Clean": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.8,
        "movement_family": "olympic",
        "pattern_class": "olympic",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Hang Power Clean": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.8,
        "movement_family": "olympic",
        "pattern_class": "olympic",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Clean Pull": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
        "movement_family": "olympic",
        "pattern_class": "olympic",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Clean and Jerk": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.9,
        "movement_family": "olympic",
        "pattern_class": "olympic",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Power Snatch": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.9,
        "movement_family": "olympic",
        "pattern_class": "olympic",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Hang Power Snatch": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.9,
        "movement_family": "olympic",
        "pattern_class": "olympic",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Snatch Pull": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
        "movement_family": "olympic",
        "pattern_class": "olympic",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Clean High Pull": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
        "humeral_plane": "frontal",
        "movement_family": "olympic",
        "pattern_class": "olympic",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Barbell Complex": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
        "movement_family": "complex",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Thruster": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "grip_style": "overhand",
        "stability_demand": 0.7,
        "movement_family": "complex",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Devil\u2019s Press": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
        "movement_family": "complex",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Farmer\u2019s Walk": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.6,
        "movement_family": "carry",
        "pattern_class": "carry",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Suitcase Carry": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "unilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.8,
        "movement_family": "carry",
        "pattern_class": "carry",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Overhead Carry": {
        "implement_type": "dumbbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.8,
        "humeral_plane": "scapular",
        "movement_family": "carry",
        "pattern_class": "carry",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Zercher Carry": {
        "implement_type": "barbell",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
        "movement_family": "carry",
        "pattern_class": "carry",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Yoke Walk": {
        "implement_type": "yoke",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
        "movement_family": "carry",
        "pattern_class": "carry",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Sandbag Carry": {
        "implement_type": "sandbag",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "gravity",
        "resistance_direction": "vertical",
        "stability_demand": 0.8,
        "movement_family": "carry",
        "pattern_class": "carry",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Sled Push": {
        "implement_type": "sled",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "horizontal",
        "stability_demand": 0.5,
        "movement_family": "push",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Sled Pull": {
        "implement_type": "sled",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "horizontal",
        "stability_demand": 0.5,
        "movement_family": "pull",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
    "Tire Flip": {
        "implement_type": "tire",
        "body_position": "standing",
        "laterality": "bilateral",
        "resistance_origin": "floor",
        "resistance_direction": "vertical",
        "stability_demand": 0.7,
        "movement_family": "hinge",
        "pattern_class": "compound",
        "biomechanics_version": 2,
        "metadata_tier": "extended",
    },
}
